# >>> L1=[1,2,3]
# >>> L1[3]
# Traceback (most recent call last):
# File "<pyshell#18>", line 1, in <module>
# L1[3]
# IndexError: list index out of range